@startuml sentralServer
package "Production hubs" {
  [HUB 1]
  [HUB 2]
}

cloud {
 [MMS]
}

[HUB 1] <--> [MMS]
[HUB 2] <--> [MMS]
[MMS] .-> [Users] : Subscription to \n specific hubs
[MMS] .-> [Archive] : Subscription to \n all hubs
[Users] <.-> [Archive] : Query
@enduml