@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
scale 2

namespace pymms {
  namespace __init__ {
  }
  namespace config {
    class Config {
      +pkgPath
      +libPath
      -__init__(self)
      +initConfig(self)
    }

  }
  namespace exceptions {
    Exception <|-- MMSError
    class MMSError {
    }

  }
  namespace gomms {
    class GoMMS {
      {static} +LIB_NAME
      +goLib
      -__init__(self)
      +productEvent(self, product, productSlug, productionHub)
      +sayHello(self)
    }

  }
  namespace productevent {
    class ProductEvent {
      -_goMMS
      -_eventProduct
      -_eventProductSlug
      -_eventProductionHub
      -__init__(self, product='', productSlug='', productionHub='')
      +product(self){@property}
      +productSlug(self){@property}
      +productionHub(self){@property}
      +product(self, value){@product.setter}
      +productSlug(self, value){@productSlug.setter}
      +productionHub(self, value){@productionHub.setter}
      +send(self)
    }

  }
  namespace pymms {
    class PyMMS {
      +goMMS
      -__init__(self)
      +helloWorld(self)
    }

  }
}
@enduml