@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

'LAYOUT_WITH_LEGEND

title Component diagram for mmsd

' perhaps better suited for Container diagram: Container(wm, "Workflow manager", "ecFlow, ProRad, ...", "Lets people construct processing pipelines")
Container(mms, "Client App", "go-mms", "Provides a user interface to the MMS system")
System_Ext(subscriber, "Consumer of ProductionHub events", "Subscribes to events from the production hub")
System_Ext(ms, "Monitoring system", "Gathers metrics")

Container_Boundary(api, "mmsd") {
    Component(mb, "Message Broker", "NATS", "Allows clients to subscribe to events and client apps to communicate with mmsd.")
    Component(pes, "Persistent Event Storage", "sqlite", "Provides a persistent storage for all events.")
    Component(restapi, "REST API", "golang", "Provides functionality for /about, /healthz, /status")
    Component(core, "core", "golang", "Provides logic and connection control.")

    Rel(core, mb, "Reads commands from private channel")
    Rel(core, pes, "Stores events")
    Rel(core, mb, "Publishes events")
    Rel(restapi, core, "Fetches data")
}

Rel(mms, mb, "Sends commands", "JSON/NATS")
Rel(subscriber, mb, "Subscribes to events", "JSON/NATS")
Rel(ms, restapi, "Gathers metrics", "JSON/HTTPS")

@enduml