@startuml
!include <C4/C4_Context>

title MMS Context Diagram

Person(product_maintainer, "Product maintainer")


System(mms, "MMS")

System_Ext(vis, "Another Production Hub, Visualisation UI or Data Service")
System_Ext(ppi, "PPI")
System_Ext(kubernetes, "Kubernetes")
System_Ext(production_hub, "Production Hub","e.g. NWP ecFlow on PPI, rcron...")

Rel(product_maintainer, production_hub, "Maintains products and configures metadata")
Rel(vis, mms, "Subscribes to product events")
Rel(production_hub, ppi, "Runs on")
Rel(mms, kubernetes, "Runs on")
Rel(production_hub, mms, "Posts information about new products")

@enduml
