@startuml productionHub
!include <C4/C4_Container>
!include <office/Users/user.puml>

LAYOUT_LEFT_RIGHT

Person(product_maintainer, "<$user> \n Product maintainer")

System_Boundary(production_hub, "Production Hub") {
    Container(wm,"Workflow Manager","e.g. ecFlow, ProRad","Producer of products")
    Container(mmsd,"mmsd","Go","MMS Daemon, core, REST API, persistent message store, NATS")
    'Container(mb, "Message broker","NATS")
}

System(production_hub_2,"Another Production Hub")
System(another_system, "Another Sytem")

Rel(wm,mmsd,"Registers products when finished","python-wrapper, cli")
Rel(product_maintainer, wm, "Maintains products and configures metadata","Workflow Manager")
Rel(another_system, mmsd, "Subscribes to events")
Rel(production_hub_2, mmsd, "Subscribes to events")

@enduml
