@startuml
!include <C4/C4_Container>

title MMS Container Diagram

left to right direction

System(production_hub, "Production hub")

System_Boundary(mms, "MMS") {
    Container(nats,"NATS JetStream","3rd party component","Persistent message queue")
    Container(mmsd,"mmsd","Go","MMS Daemon, core, REST API")
}

System(production_hub_2,"Another Production Hub")
System(another_system, "Another Sytem")

Rel(production_hub,mmsd,"Registers products when finished","HTTPS")

Rel(another_system, mms, "Subscribes to events")
Rel(production_hub_2, mms, "Subscribes to events")

Rel(mmsd, nats, "Publishes messages for a product")

@enduml
